import type { Song } from "./types";
import posterFist from "@/assets/posters/dude-fist.jpg";
import posterDiwali from "@/assets/posters/dude-diwali.jpg";
import posterGang from "@/assets/posters/dude-gang.jpg";
import posterTopGear from "@/assets/posters/dude-topgear.jpg";
import posterEmotional from "@/assets/posters/dude-emotional.jpg";
import posterReview from "@/assets/posters/dude-review.jpg";

// Built-in Dude collection. Metadata inferred from filenames.
// vibe = [hue1, hue2] used to repaint the UI per song.
export const BUILT_IN_SONGS: Song[] = [
  {
    id: "dude-trailer-blast",
    title: "Dude — Trailer Blast",
    movie: "Dude",
    language: "Tamil",
    mood: "Mass",
    singer: "Sai Abhyankkar",
    src: "/songs/dude-trailer-blast.mp3",
    poster: posterFist,
    vibe: [258, 330],
    quote: "When the trailer drops harder than the movie. Dude effect activated.",
    builtIn: true,
  },
  {
    id: "blud-is-on-his-way",
    title: "Blud Is On His Way",
    movie: "Dude",
    language: "Tamil",
    mood: "Hype",
    singer: "Sai Abhyankkar",
    src: "/songs/blud-is-on-his-way.mp3",
    poster: posterTopGear,
    vibe: [12, 280],
    quote: "Bro is not coming. Bro has arrived. Stand back.",
    builtIn: true,
  },
  {
    id: "boom-boom",
    title: "Boom Boom",
    movie: "Dude",
    language: "Telugu",
    mood: "Mass",
    singer: "Sai Abhyankkar",
    src: "/songs/boom-boom.mp3",
    poster: posterDiwali,
    vibe: [340, 30],
    quote: "Two booms. Zero rupees. Infinite reload.",
    builtIn: true,
  },
  {
    id: "singari",
    title: "Singari",
    movie: "Dude",
    language: "Telugu",
    mood: "Melody",
    singer: "Sai Abhyankkar",
    src: "/songs/singari.mp3",
    poster: posterReview,
    vibe: [300, 200],
    quote: "Some names you whisper. Some you melt into. Singari is both.",
    builtIn: true,
  },
  {
    id: "baagundu-po",
    title: "Baagundu Po",
    movie: "Dude",
    language: "Telugu",
    mood: "Hype",
    singer: "Sai Abhyankkar",
    src: "/songs/baagundu-po.mp3",
    poster: posterGang,
    vibe: [190, 280],
    quote: "Feels good. Now go. The Dude approves.",
    builtIn: true,
  },
  {
    id: "nallaru-po",
    title: "Nallaru Po",
    movie: "Dude",
    language: "Telugu",
    mood: "Hype",
    singer: "Sai Abhyankkar",
    src: "/songs/nallaru-po.mp3",
    poster: posterTopGear,
    vibe: [170, 270],
    quote: "Be good. Then leave. The Dude philosophy in two words.",
    builtIn: true,
  },
  {
    id: "kannukulla-reprise",
    title: "Kannukulla (Reprise)",
    movie: "Dude",
    language: "Tamil",
    mood: "Emotional",
    singer: "Sai Abhyankkar",
    src: "/songs/kannukulla-reprise.mp3",
    poster: posterEmotional,
    vibe: [220, 290],
    quote: "Inside the eyes — a whole movie no one else gets to watch.",
    builtIn: true,
  },
  {
    id: "oorum-blood-unplugged",
    title: "Oorum Blood (Unplugged)",
    movie: "Dude",
    language: "Tamil",
    mood: "Emotional",
    singer: "Sai Abhyankkar",
    src: "/songs/oorum-blood-unplugged.mp3",
    poster: posterFist,
    vibe: [350, 260],
    quote: "Strip the beat. The blood still hums.",
    builtIn: true,
  },
  {
    id: "nee-gunde-lona",
    title: "Nee Gunde Lona",
    movie: "Dude",
    language: "Telugu",
    mood: "Melody",
    singer: "Sai Abhyankkar",
    src: "/songs/nee-gunde-lona.mp3",
    poster: posterEmotional,
    vibe: [320, 220],
    quote: "Inside your heart — a quiet riot wearing your name.",
    builtIn: true,
  },
];
